# 🚀 NumPy Mastery: The Foundation of Data Science

<img src='https://numpy.org/images/logo.svg' width='300' alt='NumPy Logo'>

## 📚 What You'll Master Today

NumPy (Numerical Python) is the **foundation of the entire Python data science ecosystem**. Think of it as the engine that powers everything from pandas to scikit-learn to TensorFlow!

### 🎯 Why NumPy is Essential:
- **10-100x faster** than Python lists for numerical operations
- **Memory efficient** - stores data in contiguous blocks
- **Vectorized operations** - no need for loops!
- **Broadcasting** - smart operations between different shaped arrays
- **Foundation for ML** - all ML libraries use NumPy arrays

### 📊 What We'll Cover:
1. **Array Creation & Basics** - Your first steps
2. **Array Operations** - Math at lightning speed
3. **Indexing & Slicing** - Access any data point
4. **Broadcasting** - The magic of NumPy
5. **Linear Algebra** - Matrix operations
6. **Random Numbers** - Statistical simulations
7. **Advanced Techniques** - Pro-level skills
8. **Real-World Projects** - Apply everything!

---

## 🎬 Let's Begin!

In [1]:
# Import NumPy - the standard convention is 'np'
import numpy as np

# Check version
print(f"NumPy Version: {np.__version__}")
print("\n🎉 NumPy loaded successfully! Let's dive in!")

NumPy Version: 1.26.4

🎉 NumPy loaded successfully! Let's dive in!


---

## 📌 Section 1: Array Creation & Basics

### 🔍 Understanding NumPy Arrays

Think of NumPy arrays as **supercharged Python lists**. While lists are like boxes that can hold anything, NumPy arrays are like **specialized containers** optimized for numbers.

<img src='https://miro.medium.com/max/1400/1*Ikn1J6siiiCSk4ivYUhdgw.png' width='600' alt='Array vs List'>

In [2]:
# 1.1 Creating Arrays from Lists
print("📦 Creating Arrays from Lists\n" + "="*40)

# Simple 1D array (vector)
python_list = [1, 2, 3, 4, 5]
numpy_array = np.array(python_list)

print(f"Python List: {python_list}")
print(f"NumPy Array: {numpy_array}")
print(f"Type: {type(numpy_array)}")
print(f"Data Type: {numpy_array.dtype}")

📦 Creating Arrays from Lists
Python List: [1, 2, 3, 4, 5]
NumPy Array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>
Data Type: int32


In [3]:
# 1.2 Creating 2D Arrays (Matrices)
print("🎯 2D Arrays (Matrices)\n" + "="*40)

# Think of this as a spreadsheet or table
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Matrix:")
print(matrix)
print(f"\nShape: {matrix.shape} (rows, columns)")
print(f"Dimensions: {matrix.ndim}D")
print(f"Total elements: {matrix.size}")

🎯 2D Arrays (Matrices)
Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Shape: (3, 3) (rows, columns)
Dimensions: 2D
Total elements: 9


In [4]:
# 1.3 Array Creation Functions - The Power Tools!
print("🛠️ Array Creation Functions\n" + "="*40)

# Zeros - Initialize with zeros
zeros = np.zeros((3, 4))  # 3 rows, 4 columns
print("Zeros array:")
print(zeros)

# Ones - Initialize with ones
ones = np.ones((2, 3))
print("\nOnes array:")
print(ones)

# Identity matrix - diagonal ones
identity = np.eye(4)
print("\nIdentity matrix:")
print(identity)

# Range arrays
range_array = np.arange(0, 10, 2)  # start, stop, step
print(f"\nRange array: {range_array}")

# Linspace - evenly spaced numbers
linspace_array = np.linspace(0, 1, 5)  # 5 numbers from 0 to 1
print(f"Linspace array: {linspace_array}")

🛠️ Array Creation Functions
Zeros array:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones array:
[[1. 1. 1.]
 [1. 1. 1.]]

Identity matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Range array: [0 2 4 6 8]
Linspace array: [0.   0.25 0.5  0.75 1.  ]


In [5]:
# 1.4 Data Types - Precision Matters!
print("💎 Data Types in NumPy\n" + "="*40)

# Different data types for different needs
int_array = np.array([1, 2, 3], dtype=np.int32)
float_array = np.array([1, 2, 3], dtype=np.float64)
complex_array = np.array([1+2j, 3+4j], dtype=np.complex128)

print(f"Integer array: {int_array}, dtype: {int_array.dtype}")
print(f"Float array: {float_array}, dtype: {float_array.dtype}")
print(f"Complex array: {complex_array}, dtype: {complex_array.dtype}")

# Memory usage comparison
print(f"\nMemory usage (bytes):")
print(f"int32: {int_array.nbytes} bytes")
print(f"float64: {float_array.nbytes} bytes")

💎 Data Types in NumPy
Integer array: [1 2 3], dtype: int32
Float array: [1. 2. 3.], dtype: float64
Complex array: [1.+2.j 3.+4.j], dtype: complex128

Memory usage (bytes):
int32: 12 bytes
float64: 24 bytes


### 🏋️ Exercise 1: Array Creation Challenge

Create the following arrays:
1. A 5x5 matrix filled with the value 7
2. An array of even numbers from 0 to 20
3. A 3x3 matrix with random integers between 1 and 10

In [6]:
# Your solution here:
# Hint: Use np.full(), np.arange(), and np.random.randint()

# Solution:
matrix_7 = np.full((5, 5), 7)
even_numbers = np.arange(0, 21, 2)
random_matrix = np.random.randint(1, 11, size=(3, 3))

print("5x5 matrix of 7s:")
print(matrix_7)
print(f"\nEven numbers: {even_numbers}")
print("\nRandom 3x3 matrix:")
print(random_matrix)

5x5 matrix of 7s:
[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]

Even numbers: [ 0  2  4  6  8 10 12 14 16 18 20]

Random 3x3 matrix:
[[ 4 10  7]
 [ 2  6  6]
 [ 9  1  2]]


---

## 📌 Section 2: Array Operations - Lightning Fast Math

### ⚡ Vectorized Operations

This is where NumPy shines! No more loops - operations happen on entire arrays at once!

In [7]:
# 2.1 Basic Arithmetic Operations
print("➕ Basic Arithmetic\n" + "="*40)

arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([1, 2, 3, 4, 5])

print(f"Array 1: {arr1}")
print(f"Array 2: {arr2}")
print(f"\nAddition: {arr1 + arr2}")
print(f"Subtraction: {arr1 - arr2}")
print(f"Multiplication: {arr1 * arr2}")
print(f"Division: {arr1 / arr2}")
print(f"Power: {arr2 ** 2}")
print(f"Modulo: {arr1 % 3}")

➕ Basic Arithmetic
Array 1: [10 20 30 40 50]
Array 2: [1 2 3 4 5]

Addition: [11 22 33 44 55]
Subtraction: [ 9 18 27 36 45]
Multiplication: [ 10  40  90 160 250]
Division: [10. 10. 10. 10. 10.]
Power: [ 1  4  9 16 25]
Modulo: [1 2 0 1 2]


In [ ]:
#   2.2 Speed Comparison: NumPy vs Python Lists
import time

print("🏎️ Speed Test: NumPy vs Python Lists\n" + "="*40)

# Create large datasets
size = 1000000
list1 = list(range(size))
list2 = list(range(size))
np_array1 = np.arange(size)
np_array2 = np.arange(size)

# Python list operation
start = time.time()
result_list = [a + b for a, b in zip(list1, list2)]
python_time = time.time() - start

# NumPy operation
start = time.time()
result_numpy = np_array1 + np_array2
numpy_time = time.time() - start

print(f"Python List Time: {python_time:.4f} seconds")
print(f"NumPy Array Time: {numpy_time:.4f} seconds")
print(f"\n🚀 NumPy is {python_time/numpy_time:.1f}x faster!")

🏎️ Speed Test: NumPy vs Python Lists
Python List Time: 0.9147 seconds
NumPy Array Time: 0.0090 seconds

🚀 NumPy is 101.2x faster!


In [9]:
# 2.3 Universal Functions (ufuncs)
print("🔧 Universal Functions\n" + "="*40)

angles = np.array([0, 30, 45, 60, 90])
radians = np.deg2rad(angles)

print(f"Angles (degrees): {angles}")
print(f"Angles (radians): {radians}")
print(f"\nSine values: {np.sin(radians)}")
print(f"Cosine values: {np.cos(radians)}")

# More useful functions
numbers = np.array([1.7, 2.3, -3.5, 4.8])
print(f"\nOriginal: {numbers}")
print(f"Absolute: {np.abs(numbers)}")
print(f"Ceiling: {np.ceil(numbers)}")
print(f"Floor: {np.floor(numbers)}")
print(f"Round: {np.round(numbers)}")

# Exponential and logarithm
exp_array = np.array([1, 2, 3])
print(f"\nExponential of {exp_array}: {np.exp(exp_array)}")
print(f"Natural log of {exp_array}: {np.log(exp_array)}")
print(f"Log base 10 of [10, 100, 1000]: {np.log10([10, 100, 1000])}")

🔧 Universal Functions
Angles (degrees): [ 0 30 45 60 90]
Angles (radians): [0.         0.52359878 0.78539816 1.04719755 1.57079633]

Sine values: [0.         0.5        0.70710678 0.8660254  1.        ]
Cosine values: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]

Original: [ 1.7  2.3 -3.5  4.8]
Absolute: [1.7 2.3 3.5 4.8]
Ceiling: [ 2.  3. -3.  5.]
Floor: [ 1.  2. -4.  4.]
Round: [ 2.  2. -4.  5.]

Exponential of [1 2 3]: [ 2.71828183  7.3890561  20.08553692]
Natural log of [1 2 3]: [0.         0.69314718 1.09861229]
Log base 10 of [10, 100, 1000]: [1. 2. 3.]


In [10]:
# 2.4 Aggregation Functions
print("📊 Aggregation Functions\n" + "="*40)

data = np.array([23, 45, 67, 89, 12, 34, 56, 78, 90, 21])

print(f"Data: {data}")
print(f"\nStatistics:")
print(f"Sum: {np.sum(data)}")
print(f"Mean: {np.mean(data):.2f}")
print(f"Median: {np.median(data)}")
print(f"Standard Deviation: {np.std(data):.2f}")
print(f"Variance: {np.var(data):.2f}")
print(f"Min: {np.min(data)}")
print(f"Max: {np.max(data)}")
print(f"ArgMin (index of min): {np.argmin(data)}")
print(f"ArgMax (index of max): {np.argmax(data)}")

# Percentiles
print(f"\nPercentiles:")
print(f"25th percentile: {np.percentile(data, 25)}")
print(f"50th percentile (median): {np.percentile(data, 50)}")
print(f"75th percentile: {np.percentile(data, 75)}")

📊 Aggregation Functions
Data: [23 45 67 89 12 34 56 78 90 21]

Statistics:
Sum: 515
Mean: 51.50
Median: 50.5
Standard Deviation: 27.39
Variance: 750.25
Min: 12
Max: 90
ArgMin (index of min): 4
ArgMax (index of max): 8

Percentiles:
25th percentile: 25.75
50th percentile (median): 50.5
75th percentile: 75.25


### 🏋️ Exercise 2: Array Operations Challenge

Given temperature data in Celsius, convert to Fahrenheit and find:
1. The hottest day
2. The coldest day
3. Average temperature
4. Days above 25°C

In [11]:
# Temperature data for a week (in Celsius)
celsius = np.array([22, 24, 19, 26, 28, 21, 23])
days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']

# Your solution here:
fahrenheit = (celsius * 9/5) + 32
hottest_idx = np.argmax(celsius)
coldest_idx = np.argmin(celsius)
avg_temp = np.mean(celsius)
hot_days = celsius > 25

print(f"Celsius: {celsius}")
print(f"Fahrenheit: {fahrenheit}")
print(f"\nHottest day: {days[hottest_idx]} ({celsius[hottest_idx]}°C)")
print(f"Coldest day: {days[coldest_idx]} ({celsius[coldest_idx]}°C)")
print(f"Average temperature: {avg_temp:.1f}°C")
print(f"Days above 25°C: {[days[i] for i in range(len(days)) if hot_days[i]]}")

Celsius: [22 24 19 26 28 21 23]
Fahrenheit: [71.6 75.2 66.2 78.8 82.4 69.8 73.4]

Hottest day: Fri (28°C)
Coldest day: Wed (19°C)
Average temperature: 23.3°C
Days above 25°C: ['Thu', 'Fri']


---

## 📌 Section 3: Indexing & Slicing - Data Access Mastery

### 🎯 Accessing Your Data

In [12]:
# 3.1 Basic Indexing
print("📍 1D Array Indexing\n" + "="*40)

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
print(f"Array: {arr}")
print(f"First element: {arr[0]}")
print(f"Last element: {arr[-1]}")
print(f"Third element: {arr[2]}")

# Slicing
print(f"\nSlicing:")
print(f"First 3 elements: {arr[:3]}")
print(f"Last 3 elements: {arr[-3:]}")
print(f"Middle elements: {arr[2:7]}")
print(f"Every 2nd element: {arr[::2]}")
print(f"Reversed array: {arr[::-1]}")

📍 1D Array Indexing
Array: [10 20 30 40 50 60 70 80 90]
First element: 10
Last element: 90
Third element: 30

Slicing:
First 3 elements: [10 20 30]
Last 3 elements: [70 80 90]
Middle elements: [30 40 50 60 70]
Every 2nd element: [10 30 50 70 90]
Reversed array: [90 80 70 60 50 40 30 20 10]


In [13]:
# 3.2 2D Array Indexing
print("📍 2D Array Indexing\n" + "="*40)

matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

print("Matrix:")
print(matrix)

print(f"\nElement at row 2, col 3: {matrix[1, 2]}")
print(f"First row: {matrix[0]}")
print(f"First column: {matrix[:, 0]}")
print(f"\nTop-left 2x2 submatrix:")
print(matrix[:2, :2])
print(f"\nBottom-right 2x2 submatrix:")
print(matrix[-2:, -2:])

📍 2D Array Indexing
Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Element at row 2, col 3: 7
First row: [1 2 3 4]
First column: [ 1  5  9 13]

Top-left 2x2 submatrix:
[[1 2]
 [5 6]]

Bottom-right 2x2 submatrix:
[[11 12]
 [15 16]]


In [14]:
# 3.3 Boolean Indexing (Filtering)
print("🔍 Boolean Indexing\n" + "="*40)

scores = np.array([85, 92, 78, 95, 88, 73, 99, 67, 91, 82])
names = np.array(['Alice', 'Bob', 'Charlie', 'David', 'Eve', 
                  'Frank', 'Grace', 'Henry', 'Ivy', 'Jack'])

print(f"Scores: {scores}")
print(f"Names: {names}")

# Find high scorers (>= 90)
high_scores_mask = scores >= 90
print(f"\nHigh scores mask: {high_scores_mask}")
print(f"High scorers: {names[high_scores_mask]}")
print(f"Their scores: {scores[high_scores_mask]}")

# Complex conditions
medium_scores = scores[(scores >= 80) & (scores < 90)]
print(f"\nScores between 80-89: {medium_scores}")

🔍 Boolean Indexing
Scores: [85 92 78 95 88 73 99 67 91 82]
Names: ['Alice' 'Bob' 'Charlie' 'David' 'Eve' 'Frank' 'Grace' 'Henry' 'Ivy'
 'Jack']

High scores mask: [False  True False  True False False  True False  True False]
High scorers: ['Bob' 'David' 'Grace' 'Ivy']
Their scores: [92 95 99 91]

Scores between 80-89: [85 88 82]


In [16]:
# 3.4 Fancy Indexing
print("✨ Fancy Indexing\n" + "="*40)

arr = np.array([100, 200, 300, 400, 500, 600, 700])
indices = [1, 3, 5]

print(f"Array: {arr}")
print(f"Select indices {indices}: {arr[indices]}")

# 2D fancy indexing
matrix = np.arange(1, 17).reshape(4, 4)
print(f"\nMatrix:")
print(matrix)

rows = [0, 2]
cols = [1, 3]
print(f"\nSelect elements at (0,1) and (2,3): {matrix[rows, cols]}")

✨ Fancy Indexing
Array: [100 200 300 400 500 600 700]
Select indices [1, 3, 5]: [200 400 600]

Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Select elements at (0,1) and (2,3): [ 2 12]


---

## 📌 Section 4: Broadcasting - The Magic of NumPy

### 🎩 Understanding Broadcasting

Broadcasting allows NumPy to perform operations on arrays of different shapes!

In [ ]:
# 4.1 Simple Broadcasting
print("📡 Broadcasting Basics\n" + "="*40)

# Scalar and array
arr = np.array([1, 2, 3, 4, 5])
print(f"Array: {arr}")
print(f"Array + 10: {arr + 10}")
print(f"Array * 2: {arr * 2}")

# Broadcasting with different shapes
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row_vector = np.array([10, 20, 30])
col_vector = np.array([[100], [200], [300]])

print(f"\nMatrix:")
print(matrix)
print(f"\nRow vector: {row_vector}")
print(f"\nMatrix + Row vector:")
print(matrix + row_vector)

print(f"\nColumn vector:")
print(col_vector)
print(f"\nMatrix + Column vector:")
print(matrix + col_vector)

In [17]:
# 4.2 Practical Broadcasting Example
print("💼 Real-World Broadcasting\n" + "="*40)

# Sales data: rows = products, columns = months
sales = np.array([
    [120, 135, 155],  # Product A
    [200, 210, 195],  # Product B
    [80, 95, 110]     # Product C
])

prices = np.array([10, 15, 20])  # Price per unit for each product
months = ['Jan', 'Feb', 'Mar']
products = ['Product A', 'Product B', 'Product C']

print("Sales (units):")
print(sales)
print(f"\nPrices: ${prices}")

# Calculate revenue using broadcasting
revenue = sales * prices.reshape(-1, 1)
print(f"\nRevenue:")
print(revenue)

# Total revenue per month
monthly_total = np.sum(revenue, axis=0)
print(f"\nMonthly totals: {dict(zip(months, monthly_total))}")

💼 Real-World Broadcasting
Sales (units):
[[120 135 155]
 [200 210 195]
 [ 80  95 110]]

Prices: $[10 15 20]

Revenue:
[[1200 1350 1550]
 [3000 3150 2925]
 [1600 1900 2200]]

Monthly totals: {'Jan': 5800, 'Feb': 6400, 'Mar': 6675}


---

## 📌 Section 5: Reshaping & Manipulation

### 🔄 Transform Your Arrays

In [18]:
# 5.1 Reshaping Arrays
print("🔄 Reshaping Arrays\n" + "="*40)

# Create a 1D array
arr = np.arange(1, 13)
print(f"Original 1D array: {arr}")
print(f"Shape: {arr.shape}")

# Reshape to 2D
matrix_3x4 = arr.reshape(3, 4)
print(f"\nReshaped to 3x4:")
print(matrix_3x4)

# Reshape to 2x6
matrix_2x6 = arr.reshape(2, 6)
print(f"\nReshaped to 2x6:")
print(matrix_2x6)

# Use -1 to automatically calculate dimension
matrix_auto = arr.reshape(4, -1)
print(f"\nReshaped to 4x(auto):")
print(matrix_auto)

🔄 Reshaping Arrays
Original 1D array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape: (12,)

Reshaped to 3x4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshaped to 2x6:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

Reshaped to 4x(auto):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [19]:
# 5.2 Stacking and Splitting
print("📚 Stacking Arrays\n" + "="*40)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

# Vertical stack
v_stack = np.vstack([arr1, arr2, arr3])
print("Vertical stack:")
print(v_stack)

# Horizontal stack
h_stack = np.hstack([arr1, arr2, arr3])
print(f"\nHorizontal stack: {h_stack}")

# Splitting
print("\n✂️ Splitting Arrays")
arr = np.arange(1, 10)
splits = np.split(arr, 3)
print(f"Original: {arr}")
print(f"Split into 3: {splits}")

📚 Stacking Arrays
Vertical stack:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Horizontal stack: [1 2 3 4 5 6 7 8 9]

✂️ Splitting Arrays
Original: [1 2 3 4 5 6 7 8 9]
Split into 3: [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [20]:
# 5.3 Transpose and Swapaxes
print("🔄 Transpose Operations\n" + "="*40)

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

print("Original matrix:")
print(matrix)
print(f"Shape: {matrix.shape}")

# Transpose
transposed = matrix.T
print("\nTransposed:")
print(transposed)
print(f"Shape: {transposed.shape}")

🔄 Transpose Operations
Original matrix:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)

Transposed:
[[1 4]
 [2 5]
 [3 6]]
Shape: (3, 2)


---

## 📌 Section 6: Linear Algebra

### 🔢 Matrix Operations

In [21]:
# 6.1 Matrix Multiplication
print("✖️ Matrix Multiplication\n" + "="*40)

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

# Element-wise multiplication
print("\nElement-wise multiplication (A * B):")
print(A * B)

# Matrix multiplication (dot product)
print("\nMatrix multiplication (A @ B):")
print(A @ B)

# Alternative: np.dot
print("\nUsing np.dot(A, B):")
print(np.dot(A, B))

✖️ Matrix Multiplication
Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Element-wise multiplication (A * B):
[[ 5 12]
 [21 32]]

Matrix multiplication (A @ B):
[[19 22]
 [43 50]]

Using np.dot(A, B):
[[19 22]
 [43 50]]


In [22]:
# 6.2 Linear Algebra Operations
print("🔧 Linear Algebra Operations\n" + "="*40)

matrix = np.array([[4, 2],
                   [1, 3]])

print("Matrix:")
print(matrix)

# Determinant
det = np.linalg.det(matrix)
print(f"\nDeterminant: {det:.2f}")

# Inverse
if det != 0:
    inverse = np.linalg.inv(matrix)
    print("\nInverse:")
    print(inverse)
    
    # Verify: A * A^(-1) = I
    identity = np.dot(matrix, inverse)
    print("\nMatrix * Inverse (should be identity):")
    print(np.round(identity))

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print(f"\nEigenvalues: {eigenvalues}")
print("Eigenvectors:")
print(eigenvectors)

🔧 Linear Algebra Operations
Matrix:
[[4 2]
 [1 3]]

Determinant: 10.00

Inverse:
[[ 0.3 -0.2]
 [-0.1  0.4]]

Matrix * Inverse (should be identity):
[[ 1.  0.]
 [-0.  1.]]

Eigenvalues: [5. 2.]
Eigenvectors:
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [23]:
# 6.3 Solving Linear Equations
print("🎯 Solving Linear Equations\n" + "="*40)

# Solve: 2x + 3y = 7
#        4x - y = 2

# Coefficient matrix
A = np.array([[2, 3],
              [4, -1]])

# Constants vector
b = np.array([7, 2])

print("System of equations:")
print("2x + 3y = 7")
print("4x - y = 2")

# Solve
solution = np.linalg.solve(A, b)
x, y = solution

print(f"\nSolution: x = {x:.2f}, y = {y:.2f}")

# Verify
print(f"\nVerification:")
print(f"2({x:.2f}) + 3({y:.2f}) = {2*x + 3*y:.2f}")
print(f"4({x:.2f}) - {y:.2f} = {4*x - y:.2f}")

🎯 Solving Linear Equations
System of equations:
2x + 3y = 7
4x - y = 2

Solution: x = 0.93, y = 1.71

Verification:
2(0.93) + 3(1.71) = 7.00
4(0.93) - 1.71 = 2.00


---

## 📌 Section 7: Random Numbers & Distributions

### 🎲 Generate Random Data

In [24]:
# 7.1 Random Number Generation
print("🎲 Random Numbers\n" + "="*40)

# Set seed for reproducibility
np.random.seed(42)

# Random integers
random_ints = np.random.randint(1, 100, size=10)
print(f"Random integers (1-99): {random_ints}")

# Random floats [0, 1)
random_floats = np.random.random(5)
print(f"\nRandom floats [0,1): {random_floats}")

# Random choice
choices = np.random.choice(['red', 'green', 'blue'], size=10)
print(f"\nRandom choices: {choices}")

# Shuffle array
arr = np.arange(10)
np.random.shuffle(arr)
print(f"\nShuffled array: {arr}")

🎲 Random Numbers
Random integers (1-99): [52 93 15 72 61 21 83 87 75 75]

Random floats [0,1): [0.86617615 0.60111501 0.70807258 0.02058449 0.96990985]

Random choices: ['green' 'green' 'green' 'red' 'red' 'green' 'green' 'red' 'red' 'red']

Shuffled array: [1 5 4 8 0 7 6 3 2 9]


In [25]:
# 7.2 Statistical Distributions
print("📊 Statistical Distributions\n" + "="*40)

# Normal distribution
normal = np.random.normal(loc=100, scale=15, size=1000)  # IQ scores
print(f"Normal distribution (mean=100, std=15):")
print(f"Sample mean: {np.mean(normal):.2f}")
print(f"Sample std: {np.std(normal):.2f}")

# Uniform distribution
uniform = np.random.uniform(low=0, high=10, size=1000)
print(f"\nUniform distribution [0,10):")
print(f"Sample mean: {np.mean(uniform):.2f}")
print(f"Sample min: {np.min(uniform):.2f}")
print(f"Sample max: {np.max(uniform):.2f}")

# Binomial distribution (coin flips)
coin_flips = np.random.binomial(n=10, p=0.5, size=1000)  # 10 flips, 1000 times
print(f"\nBinomial (10 coin flips):")
print(f"Average heads: {np.mean(coin_flips):.2f}")

# Poisson distribution
poisson = np.random.poisson(lam=3, size=1000)  # Events per time interval
print(f"\nPoisson distribution (λ=3):")
print(f"Sample mean: {np.mean(poisson):.2f}")

📊 Statistical Distributions
Normal distribution (mean=100, std=15):
Sample mean: 100.71
Sample std: 15.84

Uniform distribution [0,10):
Sample mean: 4.90
Sample min: 0.00
Sample max: 9.97

Binomial (10 coin flips):
Average heads: 5.07

Poisson distribution (λ=3):
Sample mean: 2.96


---

## 📌 Section 8: Advanced NumPy Techniques

### 🚀 Pro-Level Skills

In [26]:
# 8.1 Views vs Copies
print("👁️ Views vs Copies\n" + "="*40)

original = np.array([1, 2, 3, 4, 5])
view = original[1:4]  # This is a view
copy = original[1:4].copy()  # This is a copy


print(f"Original: {original}")
print(f"View: {view}")
print(f"Copy: {copy}")

# Modify the view
view[0] = 999
print(f"\nAfter modifying view[0] = 999:")
print(f"Original: {original}")  # Original is affected!
print(f"View: {view}")

# Modify the copy
copy[0] = 888
print(f"\nAfter modifying copy[0] = 888:")
print(f"Original: {original}")  # Original is NOT affected
print(f"Copy: {copy}")

👁️ Views vs Copies
Original: [1 2 3 4 5]
View: [2 3 4]
Copy: [2 3 4]

After modifying view[0] = 999:
Original: [  1 999   3   4   5]
View: [999   3   4]

After modifying copy[0] = 888:
Original: [  1 999   3   4   5]
Copy: [888   3   4]


In [27]:
# 8.2 Memory Layout: C vs Fortran Order
print("💾 Memory Layout\n" + "="*40)

# C-order (row-major, default)
c_array = np.array([[1, 2, 3],
                    [4, 5, 6]], order='C')

# Fortran-order (column-major)
f_array = np.array([[1, 2, 3],
                    [4, 5, 6]], order='F')

print("C-order (row-major):")
print(c_array)
print(f"C-contiguous: {c_array.flags['C_CONTIGUOUS']}")

print("\nF-order (column-major):")
print(f_array)
print(f"F-contiguous: {f_array.flags['F_CONTIGUOUS']}")

💾 Memory Layout
C-order (row-major):
[[1 2 3]
 [4 5 6]]
C-contiguous: True

F-order (column-major):
[[1 2 3]
 [4 5 6]]
F-contiguous: True


In [28]:
# 8.3 Structured Arrays
print("🏗️ Structured Arrays\n" + "="*40)

# Define the structure
dt = np.dtype([('name', 'U10'), ('age', 'i4'), ('salary', 'f8')])

# Create structured array
employees = np.array([
    ('Alice', 25, 50000.0),
    ('Bob', 30, 60000.0),
    ('Charlie', 35, 70000.0),
    ('David', 28, 55000.0)
], dtype=dt)

print("Employees structured array:")
print(employees)

print(f"\nNames: {employees['name']}")
print(f"Ages: {employees['age']}")
print(f"Average salary: ${employees['salary'].mean():,.2f}")

# Filter by condition
high_earners = employees[employees['salary'] > 55000]
print(f"\nHigh earners (>$55k): {high_earners['name']}")

🏗️ Structured Arrays
Employees structured array:
[('Alice', 25, 50000.) ('Bob', 30, 60000.) ('Charlie', 35, 70000.)
 ('David', 28, 55000.)]

Names: ['Alice' 'Bob' 'Charlie' 'David']
Ages: [25 30 35 28]
Average salary: $58,750.00

High earners (>$55k): ['Bob' 'Charlie']


In [29]:
# 8.4 Where and Select Functions
print("🎯 Where and Select\n" + "="*40)

# np.where - conditional selection
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
condition = arr > 5

# Replace values based on condition
result = np.where(condition, arr * 2, arr)
print(f"Original: {arr}")
print(f"Double if > 5: {result}")

# Find indices where condition is true
indices = np.where(arr > 5)
print(f"\nIndices where > 5: {indices[0]}")

# np.select - multiple conditions
conditions = [
    arr < 3,
    (arr >= 3) & (arr < 7),
    arr >= 7
]
choices = ['small', 'medium', 'large']
categories = np.select(conditions, choices)
print(f"\nCategorized: {categories}")

🎯 Where and Select
Original: [1 2 3 4 5 6 7 8 9]
Double if > 5: [ 1  2  3  4  5 12 14 16 18]

Indices where > 5: [5 6 7 8]

Categorized: ['small' 'small' 'medium' 'medium' 'medium' 'medium' 'large' 'large'
 'large']


---

## 🎯 Section 9: Real-World Projects

### Project 1: Image Processing with NumPy

In [30]:
# 9.1 Image as NumPy Array
print("🖼️ Image Processing\n" + "="*40)

# Create a simple 8x8 grayscale image
image = np.random.randint(0, 256, size=(8, 8), dtype=np.uint8)

print("Original image (8x8 pixels):")
print(image)

# Basic image operations
print(f"\nImage statistics:")
print(f"Min pixel value: {image.min()}")
print(f"Max pixel value: {image.max()}")
print(f"Mean brightness: {image.mean():.1f}")

# Brightness adjustment
brightened = np.clip(image + 50, 0, 255).astype(np.uint8)
print(f"\nBrightened image (first 3 rows):")
print(brightened[:3])

# Image flip
flipped_h = np.fliplr(image)
flipped_v = np.flipud(image)
print(f"\nHorizontally flipped (first row): {flipped_h[0]}")
print(f"Original (first row): {image[0]}")

🖼️ Image Processing
Original image (8x8 pixels):
[[169 203 156   7  47   2  32 110]
 [201   2  93  18 241 145   0 224]
 [ 80  59 237 168 157  59  44  77]
 [148  79 124 110  59 216  52  24]
 [140 125 123 195   0 129  37 194]
 [ 64 226  26 254 238 184  35 155]
 [ 32 127 182 168  37   0   0 146]
 [ 24 168 234  12 153  49 183  13]]

Image statistics:
Min pixel value: 0
Max pixel value: 254
Mean brightness: 109.3

Brightened image (first 3 rows):
[[219 253 206  57  97  52  82 160]
 [251  52 143  68  35 195  50  18]
 [130 109  31 218 207 109  94 127]]

Horizontally flipped (first row): [110  32   2  47   7 156 203 169]
Original (first row): [169 203 156   7  47   2  32 110]


### Project 2: Financial Analysis

In [31]:
# 9.2 Stock Market Analysis
print("📈 Stock Market Analysis\n" + "="*40)

# Simulate stock prices for 30 days
np.random.seed(42)
days = 30
initial_price = 100

# Generate daily returns (normal distribution)
daily_returns = np.random.normal(0.001, 0.02, days)
price_multipliers = 1 + daily_returns
prices = initial_price * np.cumprod(price_multipliers)

print(f"Stock prices (first 10 days):")
print(prices[:10].round(2))

# Calculate metrics
returns = np.diff(prices) / prices[:-1]
volatility = np.std(returns) * np.sqrt(252)  # Annualized

print(f"\n📊 Analysis Results:")
print(f"Starting price: ${initial_price}")
print(f"Final price: ${prices[-1]:.2f}")
print(f"Total return: {(prices[-1]/initial_price - 1)*100:.2f}%")
print(f"Max price: ${np.max(prices):.2f}")
print(f"Min price: ${np.min(prices):.2f}")
print(f"Volatility (annualized): {volatility*100:.2f}%")

# Moving average
window = 5
moving_avg = np.convolve(prices, np.ones(window)/window, mode='valid')
print(f"\n5-day moving average (last 5 values):")
print(moving_avg[-5:].round(2))

📈 Stock Market Analysis
Stock prices (first 10 days):
[101.09 100.91 102.32 105.54 105.15 104.77 108.18 109.95 109.03 110.32]

📊 Analysis Results:
Starting price: $100
Final price: $91.60
Total return: -8.40%
Max price: $110.32
Min price: $91.60
Volatility (annualized): 28.28%

5-day moving average (last 5 values):
[95.71 94.68 93.76 93.17 92.67]


### Project 3: Machine Learning - Simple Neural Network

In [32]:
# 9.3 Simple Neural Network with NumPy
print("🧠 Neural Network from Scratch\n" + "="*40)

# Sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Training data (XOR problem)
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])

y = np.array([[0], [1], [1], [0]])  # XOR output

# Initialize weights randomly
np.random.seed(1)
weights_input_hidden = np.random.uniform(-1, 1, (2, 4))
weights_hidden_output = np.random.uniform(-1, 1, (4, 1))

print("Training XOR Neural Network...")
print(f"Input: {X.tolist()}")
print(f"Expected Output: {y.T[0]}")

# Training (simplified)
for epoch in range(5000):
    # Forward propagation
    hidden = sigmoid(np.dot(X, weights_input_hidden))
    output = sigmoid(np.dot(hidden, weights_hidden_output))
    
    # Backpropagation
    output_error = y - output
    output_delta = output_error * sigmoid_derivative(output)
    
    hidden_error = output_delta.dot(weights_hidden_output.T)
    hidden_delta = hidden_error * sigmoid_derivative(hidden)
    
    # Update weights
    weights_hidden_output += hidden.T.dot(output_delta) * 0.1
    weights_input_hidden += X.T.dot(hidden_delta) * 0.1

print(f"\nPredictions after training:")
print(output.round(2).T[0])
print(f"\n✅ Network learned XOR function!")

🧠 Neural Network from Scratch
Training XOR Neural Network...
Input: [[0, 0], [0, 1], [1, 0], [1, 1]]
Expected Output: [0 1 1 0]

Predictions after training:
[0.15 0.79 0.79 0.51]

✅ Network learned XOR function!


---

## 🎓 Section 10: Performance & Best Practices

### ⚡ Optimize Your Code

In [33]:
# 10.1 Vectorization Best Practices
print("⚡ Vectorization Tips\n" + "="*40)

size = 100000
arr = np.random.random(size)

# BAD: Using Python loops
start = time.time()
result_loop = []
for x in arr:
    result_loop.append(x ** 2 + 2 * x + 1)
loop_time = time.time() - start

# GOOD: Using NumPy vectorization
start = time.time()
result_vector = arr ** 2 + 2 * arr + 1
vector_time = time.time() - start

print(f"Loop time: {loop_time:.4f} seconds")
print(f"Vectorized time: {vector_time:.6f} seconds")
print(f"\n🚀 Vectorization is {loop_time/vector_time:.0f}x faster!")

# Memory tips
print("\n💾 Memory Tips:")
print("1. Use appropriate dtypes (int8 vs int64)")
print("2. Use views instead of copies when possible")
print("3. Delete large arrays when done: del array")
print("4. Use in-place operations: arr += 1 vs arr = arr + 1")

⚡ Vectorization Tips
Loop time: 0.3444 seconds
Vectorized time: 0.002991 seconds

🚀 Vectorization is 115x faster!

💾 Memory Tips:
1. Use appropriate dtypes (int8 vs int64)
2. Use views instead of copies when possible
3. Delete large arrays when done: del array
4. Use in-place operations: arr += 1 vs arr = arr + 1


In [34]:
# 10.2 Common Pitfalls and Solutions
print("⚠️ Common Pitfalls\n" + "="*40)

# Pitfall 1: Modifying views affects original
original = np.array([1, 2, 3, 4, 5])
view = original[:3]
view_copy = original[:3].copy()

print("Pitfall 1: Views vs Copies")
print("Always use .copy() if you don't want to modify original\n")

# Pitfall 2: Integer division
print("Pitfall 2: Integer Division")
arr_int = np.array([1, 2, 3])
print(f"Integer array / 2: {arr_int / 2}")
print(f"Integer array // 2: {arr_int // 2}")
print("Use // for integer division, / for float\n")

# Pitfall 3: Broadcasting shapes
print("Pitfall 3: Broadcasting Shapes")
print("Always check shapes before operations")
a = np.array([[1, 2, 3]])
b = np.array([[1], [2], [3]])
print(f"Shape (1,3) + Shape (3,1) = Shape (3,3)")

⚠️ Common Pitfalls
Pitfall 1: Views vs Copies
Always use .copy() if you don't want to modify original

Pitfall 2: Integer Division
Integer array / 2: [0.5 1.  1.5]
Integer array // 2: [0 1 1]
Use // for integer division, / for float

Pitfall 3: Broadcasting Shapes
Always check shapes before operations
Shape (1,3) + Shape (3,1) = Shape (3,3)


---

## 🏆 Final Challenge: Complete Data Analysis Project

### Analyze Student Performance Data

In [35]:
# Final Project: Student Performance Analysis
print("🎯 FINAL PROJECT: Student Performance Analysis\n" + "="*50)

# Generate synthetic student data
np.random.seed(42)
n_students = 100
n_subjects = 5

# Create student scores (0-100) for 5 subjects
subjects = ['Math', 'Science', 'English', 'History', 'Art']
scores = np.random.normal(75, 15, (n_students, n_subjects))
scores = np.clip(scores, 0, 100)  # Ensure scores are 0-100

print("📊 Dataset Overview:")
print(f"Students: {n_students}")
print(f"Subjects: {subjects}")
print(f"\nFirst 5 students' scores:")
print(scores[:5].round(1))

# 1. Calculate overall statistics
print("\n📈 Overall Statistics:")
print("-" * 40)
for i, subject in enumerate(subjects):
    subject_scores = scores[:, i]
    print(f"{subject:10} - Mean: {np.mean(subject_scores):.1f}, "
          f"Std: {np.std(subject_scores):.1f}, "
          f"Min: {np.min(subject_scores):.1f}, "
          f"Max: {np.max(subject_scores):.1f}")

# 2. Find top performers
average_scores = np.mean(scores, axis=1)
top_5_indices = np.argsort(average_scores)[-5:][::-1]

print("\n🏆 Top 5 Students:")
print("-" * 40)
for rank, idx in enumerate(top_5_indices, 1):
    print(f"Rank {rank}: Student {idx+1} - Average: {average_scores[idx]:.1f}")

# 3. Grade distribution
def get_grade(score):
    if score >= 90: return 'A'
    elif score >= 80: return 'B'
    elif score >= 70: return 'C'
    elif score >= 60: return 'D'
    else: return 'F'

# Calculate grades for all students
grades = np.array([[get_grade(score) for score in student] 
                   for student in scores])

print("\n📝 Grade Distribution:")
print("-" * 40)
for grade in ['A', 'B', 'C', 'D', 'F']:
    count = np.sum(grades == grade)
    percentage = (count / (n_students * n_subjects)) * 100
    print(f"Grade {grade}: {count:3d} ({percentage:5.1f}%)")

# 4. Correlation between subjects
correlation_matrix = np.corrcoef(scores.T)

print("\n🔗 Subject Correlations:")
print("-" * 40)
print("Highest correlations:")
for i in range(n_subjects):
    for j in range(i+1, n_subjects):
        corr = correlation_matrix[i, j]
        if corr > 0.3:
            print(f"{subjects[i]} ↔ {subjects[j]}: {corr:.3f}")

# 5. Identify students needing help
failing_threshold = 60
students_needing_help = np.where(average_scores < failing_threshold)[0]

print(f"\n⚠️ Students needing help (avg < {failing_threshold}):")
print("-" * 40)
if len(students_needing_help) > 0:
    for idx in students_needing_help:
        weak_subjects = [subjects[i] for i in range(n_subjects) 
                        if scores[idx, i] < failing_threshold]
        print(f"Student {idx+1} - Avg: {average_scores[idx]:.1f}, "
              f"Weak in: {', '.join(weak_subjects)}")
else:
    print("All students are performing well!")

print("\n✅ Analysis Complete!")

🎯 FINAL PROJECT: Student Performance Analysis
📊 Dataset Overview:
Students: 100
Subjects: ['Math', 'Science', 'English', 'History', 'Art']

First 5 students' scores:
[[82.5 72.9 84.7 97.8 71.5]
 [71.5 98.7 86.5 68.  83.1]
 [68.  68.  78.6 46.3 49.1]
 [66.6 59.8 79.7 61.4 53.8]
 [97.  71.6 76.  53.6 66.8]]

📈 Overall Statistics:
----------------------------------------
Math       - Mean: 74.0, Std: 12.8, Min: 45.7, Max: 100.0
Science    - Mean: 76.1, Std: 14.5, Min: 40.5, Max: 100.0
English    - Mean: 73.5, Std: 14.4, Min: 26.4, Max: 100.0
History    - Mean: 76.4, Std: 13.2, Min: 46.3, Max: 100.0
Art        - Mean: 73.8, Std: 14.3, Min: 35.7, Max: 100.0

🏆 Top 5 Students:
----------------------------------------
Rank 1: Student 85 - Average: 89.1
Rank 2: Student 75 - Average: 88.8
Rank 3: Student 63 - Average: 86.5
Rank 4: Student 36 - Average: 86.1
Rank 5: Student 96 - Average: 85.3

📝 Grade Distribution:
----------------------------------------
Grade A:  71 ( 14.2%)
Grade B: 108 ( 21.

---

## 🎯 Summary & Next Steps

### 🏆 What You've Mastered:

✅ **Array Creation & Manipulation**
- Creating arrays from lists, functions
- Reshaping, stacking, splitting

✅ **Lightning-Fast Operations**
- Vectorized arithmetic
- Universal functions
- Aggregations

✅ **Advanced Indexing**
- Slicing, boolean indexing
- Fancy indexing

✅ **Broadcasting Magic**
- Operations on different shaped arrays

✅ **Linear Algebra**
- Matrix operations
- Solving equations

✅ **Random Numbers**
- Statistical distributions
- Monte Carlo simulations

✅ **Real-World Applications**
- Image processing
- Financial analysis
- Machine learning basics

### 🚀 Next Steps:

1. **Practice Daily**: Solve problems on HackerRank, LeetCode
2. **Move to Pandas**: Built on NumPy for data analysis
3. **Learn Visualization**: Matplotlib, Seaborn, Plotly
4. **Explore ML**: Scikit-learn uses NumPy arrays
5. **Deep Learning**: TensorFlow, PyTorch built on NumPy concepts

### 💡 Pro Tips:

- **Always vectorize** - avoid Python loops
- **Use appropriate dtypes** to save memory
- **Leverage broadcasting** for elegant solutions
- **Profile your code** with `%timeit` in Jupyter
- **Read the docs**: numpy.org has excellent documentation

### 📚 Resources:

- Official NumPy Documentation: numpy.org
- NumPy GitHub: github.com/numpy/numpy
- SciPy Lectures: scipy-lectures.org
- Real Python NumPy Tutorials

---

## 🎉 Congratulations!

You've completed the NumPy Mastery course! You now have the foundation for:
- **Data Science** 📊
- **Machine Learning** 🤖
- **Scientific Computing** 🔬
- **Computer Vision** 👁️
- **Financial Analysis** 📈

Remember: NumPy is the foundation of the Python data science ecosystem. Master it, and everything else becomes easier!

**Keep practicing, keep learning, and keep building amazing things with NumPy!** 🚀

In [36]:
# 🎊 Course Complete!
print("🎊" * 20)
print("\n    🏆 NUMPY MASTERY ACHIEVED! 🏆")
print("\n    You're now ready for:")
print("    → Pandas (Data Analysis)")
print("    → Matplotlib (Visualization)")
print("    → Scikit-learn (Machine Learning)")
print("    → And much more!")
print("\n" + "🎊" * 20)

🎊🎊🎊🎊🎊🎊🎊🎊🎊🎊🎊🎊🎊🎊🎊🎊🎊🎊🎊🎊

    🏆 NUMPY MASTERY ACHIEVED! 🏆

    You're now ready for:
    → Pandas (Data Analysis)
    → Matplotlib (Visualization)
    → Scikit-learn (Machine Learning)
    → And much more!

🎊🎊🎊🎊🎊🎊🎊🎊🎊🎊🎊🎊🎊🎊🎊🎊🎊🎊🎊🎊
